"""Language-neutral code graph ontology."""

from .ontology import (
    COMMON_NODE_FIELDS,
    CONTEXT_PROFILES,
    EDGE_FIELDS,
    ONTOLOGY_NAME,
    ONTOLOGY_VERSION,
    NODE_TYPES,
    PARSER_NODE_MAPPINGS,
    QUERY_HELPERS,
    RELATION_TYPES,
    SEARCH_INDEXES,
    FieldSpec,
    NodeTypeSpec,
    ParserNodeMappingSpec,
    QueryHelperSpec,
    RelationTypeSpec,
    get_node_type,
    get_relation_type,
    node_type_names,
    relation_type_names,
    schema_payload,
)

__all__ = [
    "COMMON_NODE_FIELDS",
    "CONTEXT_PROFILES",
    "EDGE_FIELDS",
    "ONTOLOGY_NAME",
    "ONTOLOGY_VERSION",
    "NODE_TYPES",
    "PARSER_NODE_MAPPINGS",
    "QUERY_HELPERS",
    "RELATION_TYPES",
    "SEARCH_INDEXES",
    "FieldSpec",
    "NodeTypeSpec",
    "ParserNodeMappingSpec",
    "QueryHelperSpec",
    "RelationTypeSpec",
    "get_node_type",
    "get_relation_type",
    "node_type_names",
    "relation_type_names",
    "schema_payload",
]
