"""Language-neutral code graph ontology."""

from .ontology import (
    COMMON_NODE_FIELDS,
    CONTEXT_PROFILES,
    EDGE_FIELDS,
    ONTOLOGY_NAME,
    ONTOLOGY_VERSION,
    NODE_TYPES,
    PARSER_NODE_MAPPINGS,
    QUERY_HELPERS,
    RELATION_TYPES,
    SEARCH_INDEXES,
    FieldSpec,
    NodeTypeSpec,
    ParserNodeMappingSpec,
    QueryHelperSpec,
    RelationTypeSpec,
    get_node_type,
    get_relation_type,
    node_type_names,
    relation_type_names,
    schema_payload,
)
from .compatibility import (
    DEFAULT_SEMANTIC_CONSTRUCT_MAPPINGS,
    OntologyExtensionDecision,
    SemanticConstructMapping,
    decide_ontology_extension,
    evolve_cross_language_ontology,
    map_semantic_construct,
    validate_canonical_mapping,
)

__all__ = [
    "COMMON_NODE_FIELDS",
    "CONTEXT_PROFILES",
    "EDGE_FIELDS",
    "ONTOLOGY_NAME",
    "ONTOLOGY_VERSION",
    "NODE_TYPES",
    "PARSER_NODE_MAPPINGS",
    "QUERY_HELPERS",
    "RELATION_TYPES",
    "SEARCH_INDEXES",
    "FieldSpec",
    "NodeTypeSpec",
    "OntologyExtensionDecision",
    "ParserNodeMappingSpec",
    "QueryHelperSpec",
    "RelationTypeSpec",
    "SemanticConstructMapping",
    "DEFAULT_SEMANTIC_CONSTRUCT_MAPPINGS",
    "decide_ontology_extension",
    "evolve_cross_language_ontology",
    "get_node_type",
    "get_relation_type",
    "map_semantic_construct",
    "node_type_names",
    "relation_type_names",
    "schema_payload",
    "validate_canonical_mapping",
]
