use tree_sitter_language::LanguageFn;

extern "C" {
    fn tree_sitter_wat() -> *const ();
}

// SAFETY: `tree_sitter_wat` is generated by Tree-sitter and compiled from the
// pinned sources under `vendor/tree-sitter-wat` by the package build script.
pub(super) const LANGUAGE: LanguageFn = unsafe { LanguageFn::from_raw(tree_sitter_wat) };

pub(super) const NODE_TYPES: &str =
    include_str!("../../vendor/tree-sitter-wat/src/node-types.json");
