pub mod api;
pub mod cli;
pub mod db_writer;
pub mod error;
mod execution;
mod graph_rows;
mod hash;
mod normalize;
mod parser;
mod partition_builder;
mod profiles;
pub mod protocol;
mod scan;
mod semantic_enrichment;
mod staging_writer;
mod syntax_materializer;

pub use error::MaterializationError;
pub use execution::{execute_materialization_pipeline, plan_materialization};
pub use protocol::{MaterializationInput, MaterializationResult};
